name: Update README Table

on:
  push:
    paths:
      - '**/*.ipynb'
      - '**/README.md'  # Also trigger on README changes
    branches:
      - keyword        # Added your branch name
      - main          # Kept other branches for future
      - master
  # Add manual trigger option
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Debug Information
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Current directory contents:"
          ls -la
          echo "Git status:"
          git status
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbformat pyyaml
          
      - name: Update README table
        run: |
          echo "Running update script..."
          python .github/scripts/update_readme_table.py
          echo "Script completed"
          
      - name: Check for changes
        id: check_changes
        run: |
          git status
          git diff README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update README table [skip ci]"
            echo "Changes committed"
          fi
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: keyword  # Explicitly set to your branch
