title: Expanse Notebooks
description: Documentation for Expanse Notebooks
theme: jekyll-theme-cayman
markdown: kramdown
include:
  - "*.md"
  - "*.markdown"
baseurl: "/New_Expanse-Notebooks_dev"  # Updated to match your repo name

# Add navigation
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Sidebar navigation
nav:
  - title: Home
    url: /
  - title: User Guide
    url: /Expanse_Notebook_User_Guide
  - title: Format Guide
    url: /Format_Notebook
