title: Expanse Notebooks
description: Documentation for Expanse Notebooks
theme: jekyll-theme-cayman
markdown: kramdown

# Explicitly include all markdown files
include:
  - "*.md"
  - "*.markdown"

# Specify the base URL
baseurl: "/Expanse-Notebooks-dev"

# Ensure proper source of files
source: ..

# Custom sidebar data
sidebar:
  - title: Home
    url: /

  - title: Main Guides
    sublinks:
      - title: README
        url: /README
      - title: User Guide
        url: /Expanse_Notebook_User_Guide
      - title: Format Guide
        url: /Format_Notebook
