title: Expanse Notebooks
description: Documentation for Expanse Notebooks
theme: jekyll-theme-cayman
markdown: kramdown

# Explicitly include all markdown files
include:
  - "*.md"
  - "*.markdown"

# Specify the base URL
baseurl: "/Expanse-Notebooks-dev"

# Ensure proper source of files
source: ..

# Navigation
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Sidebar-like navigation
nav:
  - title: Home
    url: /
  - title: User Guide
    url: /Expanse_Notebook_User_Guide
  - title: Format Guide
    url: /Format_Notebook
