# Site settings
title: Expanse Notebooks User Guide
description: Specific User Guide for Expanse Users 
baseurl: "/Expanse-Notebooks-dev" # the subpath of your site, e.g. /blog
url: "https://sdsc-hpc-training-dev.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
