name: Notebook Monitor

on:
   push:
      paths: 
       - '**/*.ipynb'

jobs: 
  detect_notebook:
    runs-on: ubuntu-latest
             
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        

      - name: Get Notebook Details
        id: notebook_info
        run: |
          # Get the name and status of added Jupyter Notebooks
          git diff --name-status HEAD~1 HEAD | grep '^A' | grep '.ipynb$' > notebook_changes.txt


