name: Append to README on New Notebook

# Trigger the workflow when there's a push to the repository
on:
  push:
    # Only run when a notebook (*.ipynb) is added
    paths:
      - "**/*.ipynb"

jobs:
  append_to_readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Append "new notebook added" to the README.md
      - name: Append message to README.md
        run: |
          echo "new notebook added" >> README.md
          
      # Configure git and commit the changes
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      # Add and commit the changes
      - name: Commit changes
        run: |
          git add README.md
          git commit -m "New notebook added, updated README.md"
          git push

